version: '3.8'

services:
  verdaccio:
    image: verdaccio/verdaccio:5
    container_name: verdaccio-npm
    restart: unless-stopped
    ports:
      - '4873:4873'
    volumes:
      - ./verdaccio/storage:/verdaccio/storage
      - ./verdaccio/config:/verdaccio/conf
      - ./verdaccio/plugins:/verdaccio/plugins
    environment:
      - VERDACCIO_USER_UID=10001
      - VERDACCIO_USER_GID=65533
    networks:
      - npm-network

  # 可选：Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: verdaccio-nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - verdaccio
    networks:
      - npm-network

networks:
  npm-network:
    driver: bridge
